name: DO App Platform - Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger only when code is pushed to main

  workflow_dispatch:  # Optional manual trigger, no inputs

permissions:
  contents: write

jobs:
  CD:
    name: Deploy to DO App Platform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to App Platform
        run: |
          echo "Checking if app 'tams-frontend-application' exists..."
          APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep tams-frontend-application | awk '{print $1}')

          if [ -z "$APP_ID" ]; then
            echo "App not found. Creating new app..."
            doctl apps create --spec .github/frontend-app-spec.json --wait
            APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep tams-frontend-application | awk '{print $1}')
            echo "Restarting app... $APP_ID"
            doctl apps restart $APP_ID
          else
            echo "App exists. Updating spec..."
            doctl apps update $APP_ID --spec .github/frontend-app-spec.json --wait
            echo "Restarting app... $APP_ID"
            doctl apps restart $APP_ID
          fi
